# Copyright 2023 Unai Lería Fortea & Pablo Vizcaíno García

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: "itfit"
site_description: "Simple and intuitive visual simple function fitter."
site_url: "https://quanticpony.github.io/itfit/"
repo_url: "https://github.com/QuanticPony/itfit"
edit_uri: "master/docs/"
repo_name: "QuanticPony/itfit"
site_dir: "site"
watch: [README.md, itfit, examples]

nav:
- Home:
  - Overview: index.md
  - License: LICENSE.md
- Code Reference: reference/
- Examples: examples/

theme:
    name: "material"
    palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: cyan
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: cyan
      accent: light-blue
      toggle:
        icon: material/brightness-3 
        name: Switch to dark mode

    features:
      - content.code.annotate
      - content.code.copy
      - navigation.tabs
      - navigation.tracking
      - navigation.instant


plugins:
- search
- autorefs
plugins:
- search
- autorefs
- gen-files:
    scripts:
      - docs/generate_reference_docs.py
- literate-nav:
    nav_file: reference/SUMMARY.md
- mkdocstrings:
    custom_templates: templates
    default_handler: python
    handlers:
      python:
        options:
          show_source: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
